version: '3.8'

services:
  #productdb: mysql
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  #api section
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnectionString=productdb;Port=3307;Database=ProductDB;Uid=root;Pwd=root"
    depends_on: 
      - productdb
    ports:
      - "6002:80"
    restart: always    

#network section
networks:
  default:
    name: micro_network
    driver: bridge

#vollumes section
volumes:
  mysql_data:
    name: mysql_data